/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Keijiban } from "./Keijiban";
export * as factories from "./factories";
export { Keijiban__factory } from "./factories/Keijiban__factory";
